version: '3.5'

services:
  mysql:
    image: mysql/mysql-server:8.0.23
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USERNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - stacks-local
    ports:
      - "3312:3306"
  stacks-blockchain-api:
    image: blockstack/stacks-blockchain-api:latest
    container_name: stacks-blockchain-api
    restart: always
    ports:
      - "3700:3700"
      - "3999:3999"
    networks:
      - stacks-local
    depends_on:
      - postgres
    volumes:
      - ./stacks-node/bns:/bns-data
    command: ["npm", "run", "start"]
  stacks-blockchain:
    image: blockstack/stacks-blockchain:2.05.0.5.1
    container_name: stacks-blockchain
    restart: on-failure
    networks:
      - stacks-local
    depends_on:
      - stacks-blockchain-api
    volumes:
      - ./stacks-node/persistent-data/stacks-blockchain:/root/stacks-node/data
      - ./stacks-node/config:/src/stacks-node
    ports:
      - "20443:20443"
      - "20444:20444"
    command:
      [
        "/bin/stacks-node",
        "start",
        "--config",
        "/src/stacks-node/Config.toml",
      ]
networks:
  stacks-local:
    ipam:
      driver: default
